-- S.K.I.F. Puerto Rico Honbu Dojo secure portal database
-- Target: Supabase PostgreSQL
-- Run this file in the Supabase SQL editor on a new project.
--
-- Privacy choices built into this schema:
--   * No plaintext passwords (Supabase Auth owns authentication).
--   * No email duplication in application tables.
--   * No exact date of birth, SSN, government ID, card number, or bank data.
--   * Parents and students can only read records linked to their account.
--   * Instructor/admin access to student records requires an AAL2 (MFA) JWT.
--   * Sensitive writes create metadata-only audit entries.

begin;

create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public;

-- ---------- Enumerated values ----------
do $$ begin
  create type public.app_role as enum ('parent', 'student', 'instructor', 'admin');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.student_age_group as enum ('child', 'youth', 'teen', 'adult');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.student_status as enum ('active', 'inactive', 'archived');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.requirement_category as enum ('kihon', 'kata', 'kumite', 'fitness', 'character', 'attendance', 'other');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.progress_status as enum ('not_started', 'practicing', 'ready', 'mastered');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.attendance_status as enum ('present', 'late', 'absent', 'excused');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.class_session_status as enum ('scheduled', 'completed', 'cancelled');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.goal_status as enum ('active', 'completed', 'paused');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.note_visibility as enum ('family', 'staff_only');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.billing_status as enum ('open', 'paid', 'overdue', 'void');
exception when duplicate_object then null; end $$;

-- ---------- Core account and student records ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null check (char_length(btrim(full_name)) between 1 and 120),
  role public.app_role not null default 'parent',
  active boolean not null default false,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint active_profile_requires_approval check (not active or approved_at is not null)
);

-- Idempotent migration support for an earlier package version.
alter table public.profiles add column if not exists approved_at timestamptz;
update public.profiles
set approved_at = coalesce(approved_at, created_at)
where active and approved_at is null;
do $$ begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.profiles'::regclass
      and conname = 'active_profile_requires_approval'
  ) then
    alter table public.profiles
      add constraint active_profile_requires_approval check (not active or approved_at is not null);
  end if;
end $$;

comment on table public.profiles is 'Application identity, approval state, and role. Email/password remain in Supabase Auth.';
comment on column public.profiles.approved_at is 'Null only while the original registration awaits approval. Disabled approved accounts retain this timestamp.';

create table if not exists public.belt_ranks (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(btrim(name)) between 1 and 80),
  level_order integer not null unique check (level_order > 0),
  color_hex text check (color_hex is null or color_hex ~ '^#[0-9A-Fa-f]{6}$'),
  description text check (description is null or char_length(description) <= 1000),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references public.profiles(id) on delete set null,
  display_name text not null check (char_length(btrim(display_name)) between 1 and 120),
  age_group public.student_age_group not null,
  is_minor boolean not null default false,
  program text check (program is null or char_length(program) <= 120),
  current_rank_id bigint references public.belt_ranks(id) on delete set null,
  status public.student_status not null default 'active',
  joined_on date not null default current_date,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint adult_minor_consistency check (not (age_group = 'adult' and is_minor))
);

comment on table public.students is 'Minimal student profile. Store an age group, not an exact birth date, unless a documented need is established.';

create table if not exists public.guardian_students (
  guardian_user_id uuid not null references public.profiles(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  relationship text not null default 'Parent' check (char_length(btrim(relationship)) between 1 and 60),
  is_primary boolean not null default false,
  active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (guardian_user_id, student_id)
);

-- ---------- Curriculum and progress ----------
create table if not exists public.requirements (
  id uuid primary key default gen_random_uuid(),
  target_rank_id bigint not null references public.belt_ranks(id) on delete cascade,
  category public.requirement_category not null default 'other',
  title text not null check (char_length(btrim(title)) between 1 and 150),
  description text check (description is null or char_length(description) <= 1500),
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (target_rank_id, title)
);

create table if not exists public.student_requirement_progress (
  student_id uuid not null references public.students(id) on delete cascade,
  requirement_id uuid not null references public.requirements(id) on delete cascade,
  status public.progress_status not null default 'not_started',
  score smallint check (score is null or score between 0 and 100),
  family_note text check (family_note is null or char_length(family_note) <= 1000),
  assessed_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key (student_id, requirement_id)
);

-- ---------- Classes and attendance ----------
create table if not exists public.class_groups (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (char_length(btrim(name)) between 1 and 120),
  description text check (description is null or char_length(description) <= 1000),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.enrollments (
  student_id uuid not null references public.students(id) on delete cascade,
  class_group_id uuid not null references public.class_groups(id) on delete cascade,
  active boolean not null default true,
  enrolled_on date not null default current_date,
  ended_on date,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (student_id, class_group_id),
  constraint enrollment_dates_valid check (ended_on is null or ended_on >= enrolled_on)
);

create table if not exists public.class_sessions (
  id uuid primary key default gen_random_uuid(),
  class_group_id uuid not null references public.class_groups(id) on delete restrict,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  location text check (location is null or char_length(location) <= 150),
  status public.class_session_status not null default 'scheduled',
  instructor_user_id uuid references public.profiles(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint session_time_valid check (ends_at > starts_at)
);

create table if not exists public.attendance (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.class_sessions(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  status public.attendance_status not null,
  recorded_by uuid references public.profiles(id) on delete set null,
  recorded_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id, student_id)
);

-- ---------- Recognition, goals, and notes ----------
create table if not exists public.badges (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (char_length(btrim(name)) between 1 and 100),
  description text check (description is null or char_length(description) <= 1000),
  icon text check (icon is null or char_length(icon) <= 20),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.student_badges (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  badge_id uuid not null references public.badges(id) on delete cascade,
  awarded_on date not null default current_date,
  note text check (note is null or char_length(note) <= 1000),
  awarded_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (student_id, badge_id)
);

create table if not exists public.student_goals (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  title text not null check (char_length(btrim(title)) between 1 and 150),
  details text check (details is null or char_length(details) <= 1500),
  status public.goal_status not null default 'active',
  target_date date,
  family_visible boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.student_notes (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  note text not null check (char_length(btrim(note)) between 1 and 3000),
  visibility public.note_visibility not null default 'family',
  author_user_id uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- Communication, billing status, and consent ----------
create table if not exists public.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(btrim(title)) between 1 and 150),
  body text not null check (char_length(btrim(body)) between 1 and 3000),
  audience text[] not null default array['all']::text[],
  published_at timestamptz not null default now(),
  expires_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint announcement_audience_valid check (
    cardinality(audience) > 0
    and audience <@ array['all', 'parent', 'student', 'instructor', 'admin']::text[]
  ),
  constraint announcement_dates_valid check (expires_at is null or expires_at > published_at)
);

create table if not exists public.billing_items (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  description text not null check (char_length(btrim(description)) between 1 and 180),
  amount_cents integer not null check (amount_cents >= 0),
  due_on date,
  status public.billing_status not null default 'open',
  paid_at timestamptz,
  external_reference text check (external_reference is null or char_length(external_reference) <= 120),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint billing_paid_consistency check ((status = 'paid' and paid_at is not null) or status <> 'paid')
);

comment on table public.billing_items is 'Tracks amounts and status only. Never store card, bank account, or CVV data here.';

create table if not exists public.consents (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  guardian_user_id uuid not null references public.profiles(id) on delete cascade,
  consent_type text not null check (char_length(btrim(consent_type)) between 1 and 80),
  granted boolean not null,
  policy_version text not null check (char_length(btrim(policy_version)) between 1 and 40),
  recorded_at timestamptz not null default now(),
  revoked_at timestamptz,
  source text not null default 'portal' check (char_length(source) <= 40),
  constraint consent_revocation_valid check (revoked_at is null or revoked_at >= recorded_at)
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  table_name text not null,
  record_id text,
  details jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

comment on table public.audit_log is 'Metadata-only activity history. Do not put note bodies, passwords, tokens, or payment data in details.';

-- ---------- Indexes used by row-security and portal queries ----------
create index if not exists profiles_role_active_idx on public.profiles(role, active);
create index if not exists profiles_pending_approval_idx on public.profiles(created_at) where not active and approved_at is null;
create index if not exists students_user_id_idx on public.students(user_id);
create index if not exists students_status_idx on public.students(status);
create index if not exists guardian_students_student_idx on public.guardian_students(student_id) where active;
create index if not exists guardian_students_guardian_idx on public.guardian_students(guardian_user_id) where active;
create index if not exists requirements_rank_idx on public.requirements(target_rank_id, active, sort_order);
create index if not exists progress_student_idx on public.student_requirement_progress(student_id);
create index if not exists enrollments_group_idx on public.enrollments(class_group_id) where active;
create index if not exists enrollments_student_idx on public.enrollments(student_id) where active;
create index if not exists class_sessions_group_time_idx on public.class_sessions(class_group_id, starts_at);
create index if not exists attendance_student_time_idx on public.attendance(student_id, recorded_at desc);
create index if not exists student_badges_student_idx on public.student_badges(student_id, awarded_on desc);
create index if not exists student_goals_student_idx on public.student_goals(student_id, created_at desc);
create index if not exists student_notes_student_idx on public.student_notes(student_id, created_at desc);
create index if not exists announcements_published_idx on public.announcements(published_at desc);
create index if not exists billing_student_idx on public.billing_items(student_id, due_on desc);
create index if not exists consents_student_idx on public.consents(student_id, recorded_at desc);
create index if not exists audit_actor_time_idx on public.audit_log(actor_user_id, occurred_at desc);

-- ---------- Security helper functions ----------
create or replace function private.is_service_role()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, auth
as $$
  select session_user in ('postgres', 'supabase_admin')
    or coalesce(auth.jwt() ->> 'role', '') = 'service_role';
$$;

create or replace function private.current_role()
returns public.app_role
language sql
stable
security definer
set search_path = pg_catalog, public, auth
as $$
  select p.role
  from public.profiles p
  where p.id = auth.uid() and p.active = true;
$$;

create or replace function private.current_aal()
returns text
language sql
stable
security definer
set search_path = pg_catalog, auth
as $$
  select coalesce(auth.jwt() ->> 'aal', 'aal1');
$$;

create or replace function private.is_admin_aal2()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public, auth, private
as $$
  select private.is_service_role()
    or (private.current_role() = 'admin'::public.app_role and private.current_aal() = 'aal2');
$$;

create or replace function private.is_staff_aal2()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public, auth, private
as $$
  select private.is_service_role()
    or (
      private.current_role() in ('instructor'::public.app_role, 'admin'::public.app_role)
      and private.current_aal() = 'aal2'
    );
$$;

create or replace function private.is_direct_family(p_student_id uuid)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public, auth
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.active = true
      and (
        (
          p.role = 'student'::public.app_role
          and exists (
            select 1 from public.students s
            where s.id = p_student_id and s.user_id = p.id
          )
        )
        or (
          p.role = 'parent'::public.app_role
          and exists (
            select 1 from public.guardian_students gs
            where gs.student_id = p_student_id
              and gs.guardian_user_id = p.id
              and gs.active = true
          )
        )
      )
  );
$$;

create or replace function private.can_access_student(p_student_id uuid)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public, auth, private
as $$
  select private.is_staff_aal2() or private.is_direct_family(p_student_id);
$$;

revoke all on function private.is_service_role() from public;
revoke all on function private.current_role() from public;
revoke all on function private.current_aal() from public;
revoke all on function private.is_admin_aal2() from public;
revoke all on function private.is_staff_aal2() from public;
revoke all on function private.is_direct_family(uuid) from public;
revoke all on function private.can_access_student(uuid) from public;

grant usage on schema private to authenticated;
grant execute on function private.current_role() to authenticated;
grant execute on function private.current_aal() to authenticated;
grant execute on function private.is_admin_aal2() to authenticated;
grant execute on function private.is_staff_aal2() to authenticated;
grant execute on function private.is_direct_family(uuid) to authenticated;
grant execute on function private.can_access_student(uuid) to authenticated;

-- ---------- Data-maintenance and protection triggers ----------
create or replace function private.set_updated_at()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function private.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  requested_name text;
begin
  requested_name := nullif(btrim(coalesce(new.raw_user_meta_data ->> 'full_name', '')), '');
  insert into public.profiles (id, full_name, role, active)
  values (
    new.id,
    left(coalesce(requested_name, nullif(split_part(coalesce(new.email, ''), '@', 1), ''), 'Dojo member'), 120),
    'parent'::public.app_role,
    false
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create or replace function private.protect_profile_security_fields()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, private
as $$
begin
  if old.created_at is distinct from new.created_at then
    raise exception 'Account creation timestamps are immutable.' using errcode = '42501';
  end if;

  if old.role is distinct from new.role
    or old.active is distinct from new.active
    or old.approved_at is distinct from new.approved_at then
    if not private.is_service_role() and not private.is_admin_aal2() then
      raise exception 'Only an MFA-verified administrator may change account roles, approval, or activation status.' using errcode = '42501';
    end if;
  end if;
  return new;
end;
$$;

create or replace function private.protect_student_identity_fields()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, private
as $$
begin
  if old.created_at is distinct from new.created_at then
    raise exception 'Student creation timestamps are immutable.' using errcode = '42501';
  end if;

  if old.user_id is distinct from new.user_id
    or old.display_name is distinct from new.display_name
    or old.age_group is distinct from new.age_group
    or old.is_minor is distinct from new.is_minor
    or old.status is distinct from new.status
    or old.joined_on is distinct from new.joined_on
    or old.created_by is distinct from new.created_by then
    if not private.is_service_role() and not private.is_admin_aal2() then
      raise exception 'Only an MFA-verified administrator may change student identity, account linkage, or lifecycle fields.' using errcode = '42501';
    end if;
  end if;

  return new;
end;
$$;

create or replace function private.protect_attribution_field()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  field_name text := tg_argv[0];
  update_mode text := coalesce(tg_argv[1], 'preserve');
  actor uuid;
  old_value text;
begin
  if private.is_service_role() then
    return new;
  end if;

  actor := auth.uid();
  if actor is null then
    raise exception 'An authenticated account is required.' using errcode = '42501';
  end if;

  if tg_op = 'INSERT' or update_mode = 'touch' then
    new := jsonb_populate_record(new, jsonb_build_object(field_name, actor));
    return new;
  end if;

  old_value := to_jsonb(old) ->> field_name;
  new := jsonb_populate_record(new, jsonb_build_object(field_name, old_value));
  return new;
end;
$$;

create or replace function private.audit_sensitive_change()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  row_data jsonb;
  record_key text;
begin
  row_data := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  record_key := case tg_table_name
    when 'guardian_students' then nullif(concat_ws(':', row_data ->> 'guardian_user_id', row_data ->> 'student_id'), '')
    when 'student_requirement_progress' then nullif(concat_ws(':', row_data ->> 'student_id', row_data ->> 'requirement_id'), '')
    when 'enrollments' then nullif(concat_ws(':', row_data ->> 'student_id', row_data ->> 'class_group_id'), '')
    else row_data ->> 'id'
  end;

  insert into public.audit_log (actor_user_id, action, table_name, record_id, details)
  values (
    auth.uid(),
    lower(tg_op),
    tg_table_name,
    nullif(record_key, ''),
    jsonb_strip_nulls(jsonb_build_object(
      'student_id', row_data ->> 'student_id',
      'session_id', row_data ->> 'session_id',
      'status', row_data ->> 'status',
      'role', row_data ->> 'role',
      'approved_at', row_data ->> 'approved_at',
      'consent_type', row_data ->> 'consent_type'
    ))
  );
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

revoke all on function private.set_updated_at() from public;
revoke all on function private.handle_new_auth_user() from public;
revoke all on function private.protect_profile_security_fields() from public;
revoke all on function private.protect_student_identity_fields() from public;
revoke all on function private.protect_attribution_field() from public;
revoke all on function private.audit_sensitive_change() from public;

-- Re-create triggers so the file can be safely re-run after edits.
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_auth_user();

-- Backfill an inactive parent profile for Auth users that predate this schema.
insert into public.profiles (id, full_name, role, active)
select
  u.id,
  left(coalesce(nullif(btrim(u.raw_user_meta_data ->> 'full_name'), ''), nullif(split_part(coalesce(u.email, ''), '@', 1), ''), 'Dojo member'), 120),
  'parent'::public.app_role,
  false
from auth.users u
on conflict (id) do nothing;

drop trigger if exists protect_profile_security_fields on public.profiles;
create trigger protect_profile_security_fields
  before update on public.profiles
  for each row execute function private.protect_profile_security_fields();

drop trigger if exists protect_student_identity_fields on public.students;
create trigger protect_student_identity_fields
  before update on public.students
  for each row execute function private.protect_student_identity_fields();

-- Server-verified attribution. Client-supplied actor IDs are overwritten.
DO $$
declare
  item text[];
begin
  foreach item slice 1 in array array[
    array['students', 'created_by', 'preserve'],
    array['guardian_students', 'created_by', 'preserve'],
    array['enrollments', 'created_by', 'preserve'],
    array['class_sessions', 'created_by', 'preserve'],
    array['student_badges', 'awarded_by', 'preserve'],
    array['student_goals', 'created_by', 'preserve'],
    array['student_notes', 'author_user_id', 'preserve'],
    array['announcements', 'created_by', 'preserve'],
    array['billing_items', 'created_by', 'preserve'],
    array['student_requirement_progress', 'assessed_by', 'touch'],
    array['attendance', 'recorded_by', 'touch']
  ] loop
    execute format('drop trigger if exists protect_%I_attribution on public.%I', item[1], item[1]);
    execute format(
      'create trigger protect_%I_attribution before insert or update on public.%I for each row execute function private.protect_attribution_field(%L, %L)',
      item[1], item[1], item[2], item[3]
    );
  end loop;
end $$;

-- updated_at triggers
DO $$
declare
  t text;
begin
  foreach t in array array[
    'profiles','belt_ranks','students','guardian_students','requirements',
    'student_requirement_progress','class_groups','enrollments','class_sessions',
    'attendance','badges','student_goals','student_notes','announcements','billing_items'
  ] loop
    execute format('drop trigger if exists set_%I_updated_at on public.%I', t, t);
    execute format('create trigger set_%I_updated_at before update on public.%I for each row execute function private.set_updated_at()', t, t);
  end loop;
end $$;

-- metadata-only audit triggers
DO $$
declare
  t text;
begin
  foreach t in array array[
    'profiles','students','guardian_students','student_requirement_progress','attendance',
    'student_badges','student_goals','student_notes','billing_items','consents'
  ] loop
    execute format('drop trigger if exists audit_%I_changes on public.%I', t, t);
    execute format('create trigger audit_%I_changes after insert or update or delete on public.%I for each row execute function private.audit_sensitive_change()', t, t);
  end loop;
end $$;

-- ---------- Row Level Security ----------
alter table public.profiles enable row level security;
alter table public.belt_ranks enable row level security;
alter table public.students enable row level security;
alter table public.guardian_students enable row level security;
alter table public.requirements enable row level security;
alter table public.student_requirement_progress enable row level security;
alter table public.class_groups enable row level security;
alter table public.enrollments enable row level security;
alter table public.class_sessions enable row level security;
alter table public.attendance enable row level security;
alter table public.badges enable row level security;
alter table public.student_badges enable row level security;
alter table public.student_goals enable row level security;
alter table public.student_notes enable row level security;
alter table public.announcements enable row level security;
alter table public.billing_items enable row level security;
alter table public.consents enable row level security;
alter table public.audit_log enable row level security;

-- Profiles: self, active staff directory entries, or MFA-verified administrator.
drop policy if exists profiles_select_authorized on public.profiles;
create policy profiles_select_authorized on public.profiles
for select to authenticated
using (
  id = auth.uid()
  or (
    private.current_role() is not null
    and active
    and role in ('instructor'::public.app_role, 'admin'::public.app_role)
  )
  or private.is_admin_aal2()
);

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles
for update to authenticated
using (id = auth.uid() and private.current_role() is not null)
with check (id = auth.uid() and private.current_role() is not null);

drop policy if exists profiles_update_admin on public.profiles;
create policy profiles_update_admin on public.profiles
for update to authenticated
using (private.is_admin_aal2())
with check (private.is_admin_aal2());

-- Reference curriculum.
drop policy if exists belt_ranks_read on public.belt_ranks;
create policy belt_ranks_read on public.belt_ranks
for select to authenticated
using ((active and private.current_role() is not null) or private.is_staff_aal2());

drop policy if exists belt_ranks_admin_write on public.belt_ranks;
create policy belt_ranks_admin_write on public.belt_ranks
for all to authenticated
using (private.is_admin_aal2())
with check (private.is_admin_aal2());

drop policy if exists requirements_read on public.requirements;
create policy requirements_read on public.requirements
for select to authenticated
using ((active and private.current_role() is not null) or private.is_staff_aal2());

drop policy if exists requirements_admin_write on public.requirements;
create policy requirements_admin_write on public.requirements
for all to authenticated
using (private.is_admin_aal2())
with check (private.is_admin_aal2());

drop policy if exists badges_read on public.badges;
create policy badges_read on public.badges
for select to authenticated
using ((active and private.current_role() is not null) or private.is_staff_aal2());

drop policy if exists badges_admin_write on public.badges;
create policy badges_admin_write on public.badges
for all to authenticated
using (private.is_admin_aal2())
with check (private.is_admin_aal2());

-- Student identity and guardian relationships.
drop policy if exists students_select_authorized on public.students;
create policy students_select_authorized on public.students
for select to authenticated
using (private.can_access_student(id));

drop policy if exists students_insert_admin on public.students;
create policy students_insert_admin on public.students
for insert to authenticated
with check (private.is_admin_aal2());

drop policy if exists students_update_staff on public.students;
create policy students_update_staff on public.students
for update to authenticated
using (private.is_staff_aal2())
with check (private.is_staff_aal2());

drop policy if exists students_delete_admin on public.students;
create policy students_delete_admin on public.students
for delete to authenticated
using (private.is_admin_aal2());

drop policy if exists guardian_links_select_authorized on public.guardian_students;
create policy guardian_links_select_authorized on public.guardian_students
for select to authenticated
using (
  (
    active = true
    and guardian_user_id = auth.uid()
    and private.current_role() = 'parent'::public.app_role
  )
  or private.is_admin_aal2()
);

drop policy if exists guardian_links_admin_write on public.guardian_students;
create policy guardian_links_admin_write on public.guardian_students
for all to authenticated
using (private.is_admin_aal2())
with check (private.is_admin_aal2());

-- Class groups, enrollment, and sessions.
drop policy if exists class_groups_read on public.class_groups;
create policy class_groups_read on public.class_groups
for select to authenticated
using ((active and private.current_role() is not null) or private.is_staff_aal2());

drop policy if exists class_groups_admin_write on public.class_groups;
create policy class_groups_admin_write on public.class_groups
for all to authenticated
using (private.is_admin_aal2())
with check (private.is_admin_aal2());

drop policy if exists enrollments_select_authorized on public.enrollments;
create policy enrollments_select_authorized on public.enrollments
for select to authenticated
using (private.can_access_student(student_id));

drop policy if exists enrollments_staff_write on public.enrollments;
create policy enrollments_staff_write on public.enrollments
for all to authenticated
using (private.is_staff_aal2())
with check (private.is_staff_aal2());

drop policy if exists class_sessions_select_authorized on public.class_sessions;
create policy class_sessions_select_authorized on public.class_sessions
for select to authenticated
using (
  private.is_staff_aal2()
  or exists (
    select 1
    from public.enrollments e
    where e.class_group_id = class_sessions.class_group_id
      and e.active = true
      and private.is_direct_family(e.student_id)
  )
);

drop policy if exists class_sessions_staff_insert on public.class_sessions;
create policy class_sessions_staff_insert on public.class_sessions
for insert to authenticated
with check (private.is_staff_aal2());

drop policy if exists class_sessions_staff_update on public.class_sessions;
create policy class_sessions_staff_update on public.class_sessions
for update to authenticated
using (private.is_staff_aal2())
with check (private.is_staff_aal2());

drop policy if exists class_sessions_admin_delete on public.class_sessions;
create policy class_sessions_admin_delete on public.class_sessions
for delete to authenticated
using (private.is_admin_aal2());

-- Progress, attendance, and awards.
drop policy if exists progress_select_authorized on public.student_requirement_progress;
create policy progress_select_authorized on public.student_requirement_progress
for select to authenticated
using (private.can_access_student(student_id));

drop policy if exists progress_staff_write on public.student_requirement_progress;
create policy progress_staff_write on public.student_requirement_progress
for all to authenticated
using (private.is_staff_aal2())
with check (private.is_staff_aal2());

drop policy if exists attendance_select_authorized on public.attendance;
create policy attendance_select_authorized on public.attendance
for select to authenticated
using (private.can_access_student(student_id));

drop policy if exists attendance_staff_write on public.attendance;
create policy attendance_staff_write on public.attendance
for all to authenticated
using (private.is_staff_aal2())
with check (private.is_staff_aal2());

drop policy if exists student_badges_select_authorized on public.student_badges;
create policy student_badges_select_authorized on public.student_badges
for select to authenticated
using (private.can_access_student(student_id));

drop policy if exists student_badges_staff_write on public.student_badges;
create policy student_badges_staff_write on public.student_badges
for all to authenticated
using (private.is_staff_aal2())
with check (private.is_staff_aal2());

-- Goals can be maintained by the linked family or MFA-verified staff.
drop policy if exists goals_select_authorized on public.student_goals;
create policy goals_select_authorized on public.student_goals
for select to authenticated
using (
  private.is_staff_aal2()
  or (family_visible and private.is_direct_family(student_id))
);

drop policy if exists goals_insert_authorized on public.student_goals;
create policy goals_insert_authorized on public.student_goals
for insert to authenticated
with check (
  (private.is_staff_aal2() and created_by = auth.uid())
  or (private.is_direct_family(student_id) and family_visible and created_by = auth.uid())
);

drop policy if exists goals_update_authorized on public.student_goals;
create policy goals_update_authorized on public.student_goals
for update to authenticated
using (private.is_staff_aal2() or (private.is_direct_family(student_id) and created_by = auth.uid()))
with check (private.is_staff_aal2() or (private.is_direct_family(student_id) and created_by = auth.uid() and family_visible));

drop policy if exists goals_delete_authorized on public.student_goals;
create policy goals_delete_authorized on public.student_goals
for delete to authenticated
using (private.is_staff_aal2() or (private.is_direct_family(student_id) and created_by = auth.uid()));

-- Notes: family notes are visible to linked accounts; staff-only notes never are.
drop policy if exists notes_select_authorized on public.student_notes;
create policy notes_select_authorized on public.student_notes
for select to authenticated
using (
  private.is_staff_aal2()
  or (visibility = 'family'::public.note_visibility and private.is_direct_family(student_id))
);

drop policy if exists notes_insert_authorized on public.student_notes;
create policy notes_insert_authorized on public.student_notes
for insert to authenticated
with check (
  (private.is_staff_aal2() and author_user_id = auth.uid())
  or (
    private.is_direct_family(student_id)
    and visibility = 'family'::public.note_visibility
    and author_user_id = auth.uid()
  )
);

drop policy if exists notes_update_authorized on public.student_notes;
create policy notes_update_authorized on public.student_notes
for update to authenticated
using (private.is_staff_aal2() or (author_user_id = auth.uid() and private.is_direct_family(student_id)))
with check (
  private.is_staff_aal2()
  or (author_user_id = auth.uid() and private.is_direct_family(student_id) and visibility = 'family'::public.note_visibility)
);

drop policy if exists notes_delete_authorized on public.student_notes;
create policy notes_delete_authorized on public.student_notes
for delete to authenticated
using (private.is_staff_aal2() or (author_user_id = auth.uid() and private.is_direct_family(student_id)));

-- Announcements are filtered by role and publication window.
drop policy if exists announcements_select_authorized on public.announcements;
create policy announcements_select_authorized on public.announcements
for select to authenticated
using (
  private.is_staff_aal2()
  or (
    private.current_role() is not null
    and published_at <= now()
    and (expires_at is null or expires_at > now())
    and (
      'all' = any(audience)
      or private.current_role()::text = any(audience)
    )
  )
);

drop policy if exists announcements_staff_insert on public.announcements;
create policy announcements_staff_insert on public.announcements
for insert to authenticated
with check (private.is_staff_aal2() and created_by = auth.uid());

drop policy if exists announcements_staff_update on public.announcements;
create policy announcements_staff_update on public.announcements
for update to authenticated
using (private.is_staff_aal2())
with check (private.is_staff_aal2());

drop policy if exists announcements_admin_delete on public.announcements;
create policy announcements_admin_delete on public.announcements
for delete to authenticated
using (private.is_admin_aal2());

-- Billing is family/admin only. Instructors cannot access it.
drop policy if exists billing_select_authorized on public.billing_items;
create policy billing_select_authorized on public.billing_items
for select to authenticated
using (private.is_admin_aal2() or private.is_direct_family(student_id));

drop policy if exists billing_admin_write on public.billing_items;
create policy billing_admin_write on public.billing_items
for all to authenticated
using (private.is_admin_aal2())
with check (private.is_admin_aal2());

-- Consent records belong to the recording guardian and MFA-verified administrators.
drop policy if exists consents_select_authorized on public.consents;
create policy consents_select_authorized on public.consents
for select to authenticated
using (
  (
    guardian_user_id = auth.uid()
    and private.current_role() = 'parent'::public.app_role
    and private.is_direct_family(student_id)
  )
  or private.is_admin_aal2()
);

drop policy if exists consents_insert_authorized on public.consents;
create policy consents_insert_authorized on public.consents
for insert to authenticated
with check (
  private.is_admin_aal2()
  or (
    guardian_user_id = auth.uid()
    and private.current_role() = 'parent'::public.app_role
    and private.is_direct_family(student_id)
  )
);

drop policy if exists consents_update_authorized on public.consents;
create policy consents_update_authorized on public.consents
for update to authenticated
using (
  (
    guardian_user_id = auth.uid()
    and private.current_role() = 'parent'::public.app_role
    and private.is_direct_family(student_id)
  )
  or private.is_admin_aal2()
)
with check (
  (
    guardian_user_id = auth.uid()
    and private.current_role() = 'parent'::public.app_role
    and private.is_direct_family(student_id)
  )
  or private.is_admin_aal2()
);

-- Audit history is visible only to MFA-verified administrators.
drop policy if exists audit_admin_read on public.audit_log;
create policy audit_admin_read on public.audit_log
for select to authenticated
using (private.is_admin_aal2());

-- ---------- API privileges ----------
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

grant usage on schema public to service_role;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;

commit;
